- name: Write job script
  copy:
    dest: "{{ history_mailer_job_script_dir }}/{{ hm_cron_entry.name }}.sh"
    content: |
        {{ history_mailer_venv }}/bin/python \
        {{ history_mailer_dir }}/history_mailer.py \
        {% if hm_cron_entry.options|d('') %}--{{ hm_cron_entry.options.join(' --') }}{% endif %} \
        > {{ history_mailer_log_dir }}/{{ hm_cron_entry.name }}_`date +%Y%m%d`.log 2>&1

- name: Set up history mailer cron job
  cron:
    disabled: "{{ not history_mailer_enable_cron_jobs }}"
    state: "{{ hm_cron_entry.state|d('present') }}"
    name: "history_mailer: {{ hm_cron_entry.name }}"
    user: "{{ history_mailer_user }}"
    weekday: "{{ hm_cron_entry.weekday }}" # TODO: Sanity check of cron settings?
    hour: "{{ hm_cron_entry.hour|d('11') }}"
    minute: "{{ hm_cron_entry.minute|d('00') }}"
    job: "bash {{ history_mailer_job_script_dir }}/{{ hm_cron_entry.name }}.sh"
        