  - name: Stat database
    stat:
      path: "{{ history_mailer_code_dir }}/{{ hm_db_filename }}"
    register: hm_db_stat
  - name: Initialise db
    command:
      cmd: "{{ history_mailer_venv }}/bin/alembic current"
      chdir: "{{ history_mailer_code_dir }}"
    environment:
      VIRTUAL_ENV: "{{ history_mailer_venv }}"
      HISTORY_MAILER_DB: "{{ hm_db_filename }}"
    when: not hm_db_stat.stat.exists
  - name: Run migrations
    command:
      cmd: "{{ history_mailer_venv }}/bin/alembic upgrade head"
      chdir: "{{ history_mailer_code_dir }}"
    environment:
      VIRTUAL_ENV: "{{ history_mailer_venv }}"
      HISTORY_MAILER_DB: "{{ hm_db_filename }}"
    when: not hm_db_stat.stat.exists
 # TODO: There should be something here for running migrations when the database does exist
