---
- block:
  - name: Ensure history mailer directories exist
    file:
      state: directory
      path: "{{ item }}"
      owner: "{{ history_mailer_user }}"
      group: "{{ history_mailer_user }}"
    with_items:
      - "{{ history_mailer_dir }}"
      - "{{ history_mailer_job_script_dir }}"
      - "{{ history_mailer_log_dir }}"
      - "{{ history_mailer_email_template_dir }}"
  - name: Clone history mailer git repo
    git:
      dest: "{{ history_mailer_code_dir }}"
      repo: "{{ history_mailer_repo }}"
      version: "{{ history_mailer_commit_id }}"
  - name: Install dependencies
    pip:
      requirements: "{{ history_mailer_code_dir }}/requirements.txt"
      virtualenv: "{{ history_mailer_venv }}"
    environment:
      VIRTUAL_ENV: "{{ history_mailer_venv }}"
  - name: Template config file
    template:
      src: config.py.j2
      dest: "{{ history_mailer_code_dir }}/config.py"
  - name: Copy history mailer files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items: "{{ history_mailer_files }}"
  - name: Set up local databases
    include_tasks: database.yml
    loop:
      - "{{ history_mailer_staging_local_db_file }}"
      - "{{ history_mailer_production_local_db_file }}"
    loop_control:
      loop_var: hm_db_filename
  - name: Set up cron jobs
    include_tasks: cron.yml
    loop: "{{ history_mailer_cron_jobs }}"
    loop_control:
      loop_var: hm_cron_entry
    when: history_mailer_cron_jobs is defined
  become: true
  become_user: "{{ history_mailer_user }}"
